### ISSUE TITLE
Bug when transforming TS-213.xml from wab

### ISSUE THREAD

**Issue by OyvindLGjesdal** [DM2E/dm2e-gui#51]
Workflow: ae00ae19-e75a-4cc3-b030-914d16e8fcbb
which is just the basic workflow described in the help pdf.

Inputxml: 
4761d709-6923-43f7-8b48-1138a5145112  
Inputxslt:
c0d2d5bc-9fa9-4186-a577-a06ee1e4141d 

[TRACE] 2013-11-18T23:15:17.429+01:00: Status change: STARTED => FAILED
[FATAL] 2013-11-18T23:15:17.429+01:00: org.apache.jena.atlas.web.HttpException: 500 Form too large 24034272>10000000
at org.apache.jena.riot.web.HttpOp.httpResponse(HttpOp.java:458)
at org.apache.jena.riot.web.HttpOp.execHttpPostForm(HttpOp.java:326)
at com.hp.hpl.jena.sparql.modify.UpdateProcessRemoteForm.execute(UpdateProcessRemoteForm.java:68)
at eu.dm2e.grafeo.jena.SparqlUpdate.execute(SparqlUpdate.java:177)
at eu.dm2e.grafeo.jena.GrafeoImpl.postToEndpoint(GrafeoImpl.java:729)
at eu.dm2e.ws.services.publish.PublishService.run(PublishService.java:103)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
at java.util.concurrent.FutureTask.run(FutureTask.java:166)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:724)

**Comment by kba** [comment]
@kaiec:
This is an issue in the triplestore, specifically in Jetty. Must set org.eclipse.jetty.server.Request.maxFormContentSize to -1 or a very large value.

**Comment by kaiec** [comment]
This is fixed, I close
